import Head from "next/head";

import { FC, ReactElement } from 'react';

import styles from "./MainLayout.module.css";
import { Navbar } from '../Navbar';

type ChildProps = {
  children: ReactElement | ReactElement[]
}

export const MainLayout: FC<ChildProps> = ({children}):ReactElement => 
 (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>{children}</main>
    </div>
  );

